local_cpu: False # Enable local CPU RAM cache for fast access

enable_pd: True
transfer_channel: "hccl"
pd_role: "sender"
pd_pull_mode: False
pd_delay_pull: False
pd_pull_done_port: [7600, 7601]
pd_use_cpu_offload: False
pd_cpu_buffer_size: 21474836480 # 20GB
pd_peer_host: <hostip>
pd_proxy_host: <ProxyIp>
pd_proxy_port: <ProxyPort>
pd_buffer_size: 2415919104 #1207959552 # 1.xxGB
pd_buffer_device: "npu" 
save_unfull_chunk: True